### ISSUE TITLE
Ability to exclude post types from issue tracker

### ISSUE THREAD

**Issue by cbirdsong** [itmaybejj/editoria11y-wp#15]
We add a Style Guide custom post type for keeping samples of blocks/patterns/etc for easy testing when we make changes or do updates. It would be nice if these could be excluded from the issue tracker with a hook.

**Comment by itmaybejj** [comment]
Priority-wise -- I don't see myself getting around to writing custom WP hooks this year. 

But there **_is_** something built-in you can use -- does your custom post type add any classes on the page? Or--could it? If so, the base library has a function intended for just this sort of situation -- the "Turn off Editoria11y if these elements exist" setting on the module config page accepts any CSS selectors. That selector could appear anywhere in the post type -- a body class or inline.

**Comment by cbirdsong** [comment]
Oh yeah, that works with the usual `single-` classes. Only issue is that it then doesn't remove any existing pages from the issue tracker because it doesn't load on the page anymore, but if I instead do `.single-posttype *` in the "Do not flag these elements" box then it clears them out on page load.

**Comment by itmaybejj** [comment]
Oh clever; I hadn't thought to use that in that way.
