### ISSUE TITLE
Include additional metadata in issue tracker CSV export

### ISSUE THREAD

**Issue by cbirdsong** [itmaybejj/editoria11y-wp#17]
I would call out post ID and post status specifically, since we often want to filter by status, and if the ID was included it would be easy to make a column with an "edit" link in a shared spreadsheet by dropping it in the URL `wp-admin/post.php?post=<id>&action=edit`

**Comment by itmaybejj** [comment]
[1.0.15](https://github.com/itmaybejj/editoria11y-wp/releases/tag/1.0.15)
