### ISSUE TITLE
Issue tracker uses URL as unique identifier instead of post ID?

### ISSUE THREAD

**Issue by cbirdsong** [itmaybejj/editoria11y-wp#18]
It seems like the issue tracker uses the URL as the unique identifier instead of the post ID. This means that a post can have multiple entries in the list from when it was in draft as`/?p=<id>` and then entries for each different slug that has been used once it's live. It also seems like this leads to redundant/out of date entries in the issue tracker if you go to a draft post, edit it to fix the accessibility issues, and then publish it?

**Comment by itmaybejj** [comment]
Correct.

I'm planning to add the ID in my next release. I avoided it at first because it is not always available, but I clearly need it now for disambiguation and advanced filtering.

**Comment by itmaybejj** [comment]
[1.0.15](https://github.com/itmaybejj/editoria11y-wp/releases/tag/1.0.15)
