### ISSUE TITLE
Super Admin Access

### ISSUE THREAD

**Issue by tryonegg** [itmaybejj/editoria11y-wp#20]
If the plugin is running on a site in a multisite environment and the current user is a Super Admin who is not assiged a role on a specific site then the editor scripts will not load them them. This is because while the user will have full access to that site they are not assigned a role (admin, editor, contributor...) by WP to that site. 

PR #19 has a fix that will load the editor scripts if the current user is a super admin.

**Comment by itmaybejj** [comment]
PR merged; will group into next release. 
I should look into https://github.com/itmaybejj/editoria11y-wp/issues/11 at the same time...
