### ISSUE TITLE
Multisite Support

### ISSUE THREAD

**Issue by silsbyc** [itmaybejj/editoria11y-wp#22]
I notice that when I enable the plugin on an individual site within our Multisite, the proper tables  *_ed11y_dismissals, *_ed11y_results, *_ed11y_urls are created for the individual site.

However, if I try to activate the plugin as a network-wide plugin, those same tables do not get created. 

Is it possible to create those tables if they don't exist on a Multisite activation?

**Comment by itmaybejj** [comment]
I'm afraid the [version with this fixed](https://github.com/itmaybejj/editoria11y-wp/commit/a2d21dde2320f50adfa6a2051e5790bfd67438b1) isn't quite ready for release yet -- I have approval to throw time at it later this spring.

**Comment by itmaybejj** [comment]
I'm hoping merging the above fixed this issue, but I'm adding a lazy provisioner in the next release that will do a one-time extra attempt to create the tables -- that should fix any older sites.

**Comment by itmaybejj** [comment]
[PR 26 fixes this.](https://github.com/itmaybejj/editoria11y-wp/pull/26) I hope to have that out shortly; if you have a dev environment I would really appreciate help testing.

**Comment by silsbyc** [comment]
But, good news is that the *_ed11y_dismissals, *_ed11y_results, *_ed11y_urls are created for sites when enabled network-wide. So this issue is definitely resolved.
