### ISSUE TITLE
Support for WordPress Classic Editor

### ISSUE THREAD

**Issue by beckej13820** [itmaybejj/editoria11y-wp#25]
Hello,

My institution runs a WordPress Multisite that is running the Pressbooks suite of plugins. These plugins transform a wordpress multisite into a book authoring platform, where each subsite is a book and you are able to export PDFs and EPUBs of the printed materials.

Pressbooks uses the Classic Editor only, with no support for Gutenberg. I was curious if the classic editor could be supported by the Editoria11y plugin.

I have installed Editoria11y on my Pressbooks network, and I have some of the same issues that most multisites have that have been reported elsewhere, that books where I activated the plugin works fine, but if I network activate, some tables are not made and the reports portion of the plugin doesn't work.

Editoria11y is marking accessibility errors for logged in viewers when previewing a page or looking at the site, but if there was support for the classic editor, they would see those in-line.

Is support for the Classic Editor possible?

**Comment by itmaybejj** [comment]
Rewriting the multisite support is up next for me, project wise. I'm rather embarrassed it's still not working right. 

As for the classic editor -- honestly; Princeton is very generous with funding this project, but I try to only ask for allotments for features we would use here. Which is to say: I would be very, very happy to provide help and support to anybody that wanted to take a whack at it, but I don't see me doing it myself.

_That said_ -- this is me thinking about the existing live checker, which was hard-coded as a hacky layer on top of the block editor. That was very much the first iteration. I'm hoping to rewrite it this summer/fall to look a lot more like spellcheck, and to have that rewrite be platform independent -- I want it to work in both Gutenberg and CKEditor. It's...a bit of a long shot, but if it _works_, it _should_ become possible to inject that code into the TinyMCE iframe pretty much unmodified, assuming WordPress allows messing with the contents of that iframe without majorly messing with core functionality.

**Comment by itmaybejj** [comment]
Actually -- the last release should have (maybe) [fixed the multisite activation bug](https://github.com/itmaybejj/editoria11y-wp/commit/a2d21dde2320f50adfa6a2051e5790bfd67438b1).

But it will not have provisioned the tables for sites that had been set up previously. I'll get that out shortly -- and that will include a lazy provisioner for the tables, so even if network creation of tables fails, the individual sites should provision their own tables the first time they run.

**Comment by itmaybejj** [comment]
Hello again.

I have a [working prototype](https://github.com/itmaybejj/editoria11y/issues/22) of a true live-editing overlay and would love some feedback.

Once this lands, all that would be needed to get it working in the classic editor would be an injection of the JS into the TinyMCE iframe.

**Comment by beckej13820** [comment]
I just saw this message. I will try to install that branch on a site and play with it a little.

**Comment by itmaybejj** [comment]
Oh there's no WP integration yet -- I'm doing the library work first. I'll be in touch when there's something turnkey that is testable!

**Comment by itmaybejj** [comment]
Ahh well; I am sorry to say after [tagging the rewrite](https://wordpress.org/plugins/editoria11y-accessibility-checker/) that I will not be supporting the classic editor. I tried, and it was just fiddly in a way that made me very nervous about corrupting content.

If somebody that knew more about the workings of the editor wanted to take a whack at it, I could talk them through what is needed. It is not _**much**_, I just need to be able to safely insert elements into the body of the iframe without them being picked up by the editor as part of the content. The other editors I am supporting have a distinct `contenteditable` wrapper around the user content, surrounded by static HTML. It's quite likely there's some function or or API in the classic editor to allow for that sort of thing.

**Comment by itmaybejj** [comment]
It's a year later but...[it looks like I'll have Classic support ready in September.](https://github.com/itmaybejj/editoria11y-wp/pull/43)

**Comment by beckej13820** [comment]
And awesome! Thanks!
