### ISSUE TITLE
Open details element if the issue is inside it

### ISSUE THREAD

**Issue by cbirdsong** [itmaybejj/editoria11y-wp#27]
Currently the popover does not work very well if there are issues with content inside of a `<details>`:

![editoria11y popup disconnected from its arrow and pointing at a collapsed details element](https://github.com/itmaybejj/editoria11y-wp/assets/1672206/572a79da-359a-410d-bbd2-2ae03daedb1e)
![editoria11y popup correctly pointing at a link inside of an open details element](https://github.com/itmaybejj/editoria11y-wp/assets/1672206/53f9265d-d4ce-4981-a15b-cc626831ac9a)

It seems like it ought to be possible to add `open` to `<details>` elements containing highlighted issues?

**Comment by itmaybejj** [comment]
Ahh lucky you -- this is already fixed in the dev branch, and I'm trying to get a release out this week.

**Comment by itmaybejj** [comment]
If you are interested in testing, [PR 26 includes this.](https://github.com/itmaybejj/editoria11y-wp/pull/26)

**Comment by itmaybejj** [comment]
[1.0.15](https://github.com/itmaybejj/editoria11y-wp/releases/tag/1.0.15)
