### ISSUE TITLE
usermeta table

### ISSUE THREAD

**Issue by silsbyc** [itmaybejj/editoria11y-wp#29]
I get errors saying the table doesn't exist for the calls in src/controller/class-editoria11y-api-results.php:186 and class-editoria11y-api-dismissals.php:202

It appears that this is related to the definition of $user_meta  = $wpdb->prefix . 'usermeta' on src/admin.php:754, src/controller/class-editoria11y-api-dismissals.php: 168, and src/controller/class-editoria11y-api-results.php:121.

Not sure if this is specific to our database, or Wordpress Multisite in general, but our usermeta tables cannot be called directly using SQL with the same structure as a site table. They are a network-wide table as opposed to site-specific tables. If this is just because of our database, you can close this, and I'll just figure out a workaround.

Deleting these specific variable definitions, and the portions of the direct DB calls that used those variables seems to have stopped the errors. I realize this means I won't be able to attribute specific dismissals to specific users. But is there anything else that would be affected by removing these direct DB calls?

**Comment by itmaybejj** [comment]
Oh dear.

No; these DB calls are not needed for any _recording_ purposes at all -- they are just there to replace the user ID number with their human readable nice name.

How do you access user information? Will [WP_User_Query](https://developer.wordpress.org/reference/classes/wp_user_query/) work? If so, I can replace the join against the user table with a second DB hit to run a WP_User_Query to get a list of nicknames.

**Comment by silsbyc** [comment]
Yes, WP_User_Query should work.

**Comment by itmaybejj** [comment]
🫡 Let's hope [1.0.16](https://github.com/itmaybejj/editoria11y-wp/releases/tag/1.0.16) works then

**Comment by itmaybejj** [comment]
Oh...missed one, in the CSV export. I'll include that in the next release.

**Comment by itmaybejj** [comment]
fixed in 1.0.17
