### ISSUE TITLE
Dashboard fails with FSE themes

### ISSUE THREAD

**Issue by beckej13820** [itmaybejj/editoria11y-wp#3]
Hi! Thank you for your plugin.

I first installed the plugin on my main website, ed-beck.com and I noticed a two issues:

1. The Dashboard never filled with errors.
2. I could not enter the Full Site Editor Template Editor. It would freeze each time I loaded it.

Turning off Editoria11y fixed the FSE issue.

To try to replicate, since my main site uses 14 different plugins, I installed a fresh WordPress Site, and only enabled the Twenty-Twenty-Three Theme, the Gutenberg Plugin, and Editorially. Unfortunately, I was not able to replicate the second problem, where the Full Site Editor froze, but on my new site, I still was not seeing any errors in the dashboard, despite the plugin displaying errors in both the editing user interface and the logged-in page view.

Here are the errors from the error log of the fresh WordPress site:

If there is anything I can do to help you replicate, or if you need a different error report to troubleshoot, please let me know, and I will help the best I can.

[07-Feb-2023 13:06:24 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SELECT
				wp_ed11y_dismissals.result_key,
				wp_ed11y_dismissals.element_id,
				wp_ed11y_dismissals.dismissal_status
				FROM wp_ed11y_dismissals
				INNER JOIN wp_ed11y_urls ON wp_ed11y_urls.pid=wp_ed11y_dismissals.pid
				WHERE wp_ed11y_urls.page_url = 'http://demo.ed-beck.com/FSE'
				AND (
					wp_ed11y_dismissals.dismissal_status = 'ok'
						OR
						(
							wp_ed11y_dismissals.dismissal_status = 'hide'
							AND
							wp_ed11y_dismissals.user = 1
						)
					)
				; made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('wp-includes/template-canvas.php'), wp_footer, do_action('wp_footer'), WP_Hook->do_action, WP_Hook->apply_filters, ed11y_init
[07-Feb-2023 13:06:26 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SELECT pid FROM wp_ed11y_urls
				WHERE page_url='http://demo.ed-beck.com/FSE'; made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Editoria11y_Api_Results->update_item, Editoria11y_Api_Results->send_results, Editoria11y_Api_Results->get_pid
[07-Feb-2023 13:41:35 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SELECT
						wp_ed11y_urls.pid,
						wp_ed11y_urls.page_url,
						wp_ed11y_urls.page_title,
						wp_ed11y_urls.entity_type,
						wp_ed11y_urls.page_total,
						MAX(wp_ed11y_results.created) AS created
					FROM wp_ed11y_urls
					INNER JOIN wp_ed11y_results ON wp_ed11y_urls.pid=wp_ed11y_results.pid
					GROUP BY wp_ed11y_urls.pid,
							wp_ed11y_urls.page_url,
							wp_ed11y_urls.page_title,
							wp_ed11y_urls.entity_type,
							wp_ed11y_urls.page_total
					ORDER BY page_total DESC
					LIMIT 25
					OFFSET 0
					; made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Editoria11y_Api_Results->get_results
[07-Feb-2023 13:41:36 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SELECT
					SUM(wp_ed11y_results.result_count) AS count,
					wp_ed11y_results.result_key
					FROM wp_ed11y_results
					INNER JOIN wp_ed11y_urls ON wp_ed11y_results.pid=wp_ed11y_urls.pid
					GROUP BY wp_ed11y_results.result_key
					ORDER BY SUM(wp_ed11y_results.result_count) DESC
					LIMIT 25
					OFFSET 0
					; made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Editoria11y_Api_Results->get_results
[07-Feb-2023 13:41:36 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SELECT
					wp_ed11y_urls.pid,
					wp_ed11y_urls.page_url,
					wp_ed11y_urls.page_title,
					wp_ed11y_urls.entity_type,
					wp_users.display_name,
					wp_ed11y_dismissals.result_key,
					wp_ed11y_dismissals.dismissal_status,
					MAX(wp_ed11y_dismissals.created) AS created,
					wp_ed11y_dismissals.stale
					FROM wp_ed11y_dismissals
					INNER JOIN wp_ed11y_urls ON (wp_ed11y_dismissals.pid=wp_ed11y_urls.pid)
					LEFT JOIN wp_users ON (wp_users.ID=wp_ed11y_dismissals.user)
					
					GROUP BY
					wp_ed11y_urls.pid,
					wp_ed11y_urls.page_url,
					wp_ed11y_urls.page_title,
					wp_ed11y_urls.entity_type,
					wp_users.display_name,
					wp_ed11y_dismissals.result_key,
					wp_ed11y_dismissals.dismissal_status,
					wp_ed11y_dismissals.stale
					ORDER BY wp_ed11y_dismissals.created DESC
					LIMIT 25
					OFFSET 0
					; made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Editoria11y_Api_Dismissals->get_dismissals
[07-Feb-2023 13:41:36 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SELECT
					MAX(wp_ed11y_dismissals.created) AS created
					FROM wp_ed11y_dismissals
					INNER JOIN wp_ed11y_urls ON (wp_ed11y_dismissals.pid=wp_ed11y_urls.pid)
					
					GROUP BY
					wp_ed11y_urls.pid,
					wp_ed11y_dismissals.user,
					wp_ed11y_dismissals.result_key,
					wp_ed11y_dismissals.dismissal_status,
					wp_ed11y_dismissals.stale
					; made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Editoria11y_Api_Dismissals->get_dismissals
[07-Feb-2023 14:13:14 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SELECT
				wp_ed11y_dismissals.result_key,
				wp_ed11y_dismissals.element_id,
				wp_ed11y_dismissals.dismissal_status
				FROM wp_ed11y_dismissals
				INNER JOIN wp_ed11y_urls ON wp_ed11y_urls.pid=wp_ed11y_dismissals.pid
				WHERE wp_ed11y_urls.page_url = 'http://demo.ed-beck.com/FSE'
				AND (
					wp_ed11y_dismissals.dismissal_status = 'ok'
						OR
						(
							wp_ed11y_dismissals.dismissal_status = 'hide'
							AND
							wp_ed11y_dismissals.user = 1
						)
					)
				; made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('wp-includes/template-canvas.php'), wp_footer, do_action('wp_footer'), WP_Hook->do_action, WP_Hook->apply_filters, ed11y_init
[07-Feb-2023 14:13:16 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SHOW FULL COLUMNS FROM `wp_ed11y_urls` made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Editoria11y_Api_Results->update_item, Editoria11y_Api_Results->send_results
[07-Feb-2023 14:13:16 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SELECT pid FROM wp_ed11y_urls
				WHERE page_url='http://demo.ed-beck.com/FSE'; made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Editoria11y_Api_Results->update_item, Editoria11y_Api_Results->send_results, Editoria11y_Api_Results->get_pid
[07-Feb-2023 14:13:16 UTC] WordPress database error Table 'edbecksu_wp3.wp_ed11y_urls' doesn't exist for query SELECT pid FROM wp_ed11y_urls
				WHERE page_url='http://demo.ed-beck.com/FSE'; made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Editoria11y_Api_Results->update_item, Editoria11y_Api_Results->send_results, Editoria11y_Api_Results->get_pid

**Comment by itmaybejj** [comment]
Drat; that means the activation functions never even ran -- none of the DB tables were installed.

Is there anything you could tell me about your environment so I can try to replicate the problem? Ideally PHP and MySql or MariaDB version?

**Comment by beckej13820** [comment]
I'm an Educational Technologist working for the State University of New York. Both WordPress sites were installed on SUNY's shared hosting service (Reclaim Hosting is our vendor). From cPanel, both sites were installed via Installatron's WordPress Installer.

## About ed-beck.com (the original site that failed)
WP 6.1.1
Active Theme: Riverbank (a full site editing theme by Theme Isle)



Server architecture | Linux 3.10.0-957.21.3.el7.x86_64 x86_64
Web server | Apache
PHP version | 8.0.25 (Supports 64bit values)
PHP SAPI | cgi-fcgi
PHP max input variables | 1000
PHP time limit | 30
PHP memory limit | 128M
PHP memory limit (only for admin screens) | 256M
Max input time | 60
Upload max filesize | 64M
PHP post max size | 1000M
cURL version | 7.86.0 OpenSSL/1.1.1s
Is SUHOSIN installed? | No
Is the Imagick library available? | Yes
Are pretty permalinks supported? | Yes
.htaccess rules | Custom rules have been added to your .htaccess file.

Database
Extension | mysqli
Server version | 5.7.30
Client version | mysqlnd 8.0.25
Database charset | utf8mb4
Database collation | utf8mb4_unicode_520_ci
Max allowed packet size | 268435456
Max connections number | 151

## About demo.ed-beck.com/FSE (the second site I spun up to try to replicate the problem)

WP 6.1.1
Active Theme | Twenty Twenty Three


Server architecture | Linux 3.10.0-957.21.3.el7.x86_64 x86_64
Web server | Apache
PHP version | 7.4.33 (Supports 64bit values)
PHP SAPI | cgi-fcgi
PHP max input variables | 1000
PHP time limit | 30
PHP memory limit | 196M
PHP memory limit (only for admin screens) | 256M
Max input time | 60
Upload max filesize | 150M
PHP post max size | 150M
cURL version | 7.86.0 OpenSSL/1.1.1s
Is SUHOSIN installed? | No
Is the Imagick library available? | Yes
Are pretty permalinks supported? | Yes
.htaccess rules | Custom rules have been added to your .htaccess file.


Database
Extension | mysqli
Server version | 5.7.30
Client version | mysqlnd 8.0.25
Database charset | utf8mb4
Database collation | utf8mb4_unicode_520_ci
Max allowed packet size | 268435456
Max connections number | 151

**Comment by itmaybejj** [comment]
Thank you so much for that. Replicated it as well as I could and it looks like your setup does not like the size of the DB table keys.

I'll get a new version out later today that will hopefully work!

**Comment by itmaybejj** [comment]
[New version](https://wordpress.org/plugins/editoria11y-accessibility-checker/) posted; please do tell me if the install works.

**Comment by beckej13820** [comment]
Updated and working! Thank you!

**Comment by itmaybejj** [comment]
Fantastic
