### ISSUE TITLE
Bug: UI in the Gutenberg editor appears to be broken after update to WP 6.6 or greater

### ISSUE THREAD

**Issue by Firestorm980** [itmaybejj/editoria11y-wp#36]
Hello. We're using editoria11y on a WordPress site using the official plugin here: https://wordpress.org/plugins/editoria11y-accessibility-checker/

We've been preparing to implement the plugin on a site that started at WordPress version 6.5.5 or lower. Originally, the UI when editing a post appeared as such: 
![image](https://github.com/user-attachments/assets/2f827799-f077-4376-a93f-df8b03bab278)
Note the "2 issues" button that would toggle visibility of issues that editoria11y would find during the editing process.

When updating to version 6.6 or more of WordPress, the button no longer appears:
![image](https://github.com/user-attachments/assets/b916bf44-8671-4974-9953-8394355d24ba)
This screenshot was taken with version 6.6.2, but I've confirmed this is also true for version 6.6.

We're currently using the editoria11y plugin with default settings (no changes) and the latest version as of writing 1.0.20.

In those newer versions of WordPress, there is a new control in the center of the bar:
![image](https://github.com/user-attachments/assets/adfa04c1-3c1c-4235-ae07-a3882b0affd9)

So, it is possible that this update maybe changed markup or hooks to allow the editoria11y toggle to appear.

Let me know if you have further questions or need help recreating / testing. I've tested this on a vanilla install of WordPress using Local, so it should be pretty easy to test. For a post, I just made something where I knew the content would be flagged (missing alt text, missing table headings, etc.)

**Comment by itmaybejj** [comment]
[This should work for now.](https://github.com/itmaybejj/editoria11y-wp/releases/tag/1.0.21). Thank you for reporting this!
