### ISSUE TITLE
Is this intended behavior for external links?

### ISSUE THREAD

**Issue by cbirdsong** [itmaybejj/editoria11y-wp#5]
On a client's site, the external link check blocks out the entire paragraph in the editor:

https://user-images.githubusercontent.com/1672206/233201154-d65fc765-eb78-45c5-89d1-0c2c4b91e5ac.mp4

Is this how it's supposed to work?

**Comment by itmaybejj** [comment]
Oh dear. That should be a fine hairline around the block, with the issue title at the bottom **_right_**.

I will see if I can replicate and fix this tomorrow. I'm assuming it has something to do with positioning or is z indexing in the block.

For now you should be able to disable the live check altogether on that site, unless that setting is one of the ones not saving changes.

**Comment by itmaybejj** [comment]
I haven't reproduced this yet but I've thrown a pile of CSS against the usual suspects in [1.0.9](https://github.com/itmaybejj/editoria11y-wp/releases/tag/1.0.9)...please do holler if you are able to test.

If it **_isn't_** fixed, I would dearly love a screenshot of what your Web inspector is showing for the computed CSS for the ::after on that block.

**Comment by cbirdsong** [comment]
This looks correct now, though it is a little odd in a block with multiple links:

![CleanShot 2023-04-20 at 08 39 39](https://user-images.githubusercontent.com/1672206/233384238-020230aa-8fb2-4c90-8735-7740d140039b.png)

Going to make a separate issue about that.
