### ISSUE TITLE
Some modified settings are not reflected on the settings page

### ISSUE THREAD

**Issue by cbirdsong** [itmaybejj/editoria11y-wp#6]
When I edit a setting with a `<select>` box and hit save, the value changes and is reflected in how the plugin works, but the new value does not have `selected` added to its `<option>` on the options page, which means it will be overwritten with the default next time the save button is pressed.

Video showing the problem: 

https://user-images.githubusercontent.com/1672206/233202787-7de87598-f355-4521-9f91-7511a1107f3c.mp4

**Comment by itmaybejj** [comment]
Fixed in [v1.0.9](https://github.com/itmaybejj/editoria11y-wp/releases/tag/1.0.9) -- thank you for alerting me to this!
